[server]
port = 5000
address = "0.0.0.0"
headless = true
enableCORS = false

[theme]
base="dark"
primaryColor="#9333ea"
backgroundColor="#212529"
secondaryBackgroundColor="#343a40"
textColor="#f8f9fa"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = true
